import React, { useState } from "react";
import { DataContext } from "./CardContext";

function CardProvider({ children }) {
  const [card, setCard] = useState([
    {
      name: "Expresso Tradicional",
      description: "O tradicional café feito com água quente e grãos moídos",
      img: "./public/card-img1.png",
      type: ["Tradicional"],
      price: 9.9,
      count: 0,
      id: 1,
      total: 0,
      favorite: false,
      isSelected: false,
    },
    {
      name: "Expresso Americano",
      description: "Expresso diluído, menos intenso que o tradicional",
      img: "./public/card-img2.png",
      type: ["Tradicional"],
      price: 10.5,
      count: 0,
      id: 2,
      total: 0,
      favorite: false,
      isSelected: false,
    },
    {
      name: "Expresso Cremoso",
      description: "Café expresso tradicional com espuma cremosa",
      img: "./public/card-img3.png",
      type: ["Tradicional"],
      price: 11.0,
      count: 0,
      id: 3,
      total: 0,
      favorite: false,
      isSelected: false,
    },
    {
      name: "Expresso Gelado",
      description: "Bebida preparada com café expresso e cubos de gelo",
      img: "./public/card-img4.png",
      type: ["Tradicional", "Gelado"],
      price: 12.3,
      count: 0,
      id: 4,
      total: 0,
      favorite: false,
      isSelected: false,
    },
    {
      name: "Café com Leite",
      description: "Meio a meio de expresso tradicional com leite vaporizado",
      img: "./public/card-img5.png",
      type: ["Tradicional", "Com leite"],
      price: 10.0,
      count: 0,
      id: 5,
      total: 0,
      favorite: false,
      isSelected: false,
    },
    {
      name: "Latte",
      description:
        "Uma dose de café expresso com o dobro de leite e espuma cremosa",
      img: "./public/card-img6.png",
      type: ["Tradicional", "Com leite"],
      price: 13.5,
      count: 0,
      id: 6,
      total: 0,
      favorite: false,
      isSelected: false,
    },
    {
      name: "Capuccino",
      description:
        "Bebida com canela feita de doses iguais de café, leite e espuma",
      img: "./public/card-img7.png",
      type: ["Tradicional", "Com leite"],
      price: 14.2,
      count: 0,
      id: 7,
      total: 0,
      favorite: false,
      isSelected: false,
    },
    {
      name: "Macchiato",
      description:
        "Café expresso misturado com um pouco de leite quente e espuma",
      img: "./public/card-img8.png",
      type: ["Tradicional", "Com leite"],
      price: 12.8,
      count: 0,
      id: 8,
      total: 0,
      favorite: false,
      isSelected: false,
    },
    {
      name: "Mocaccino",
      description: "Café expresso com calda de chocolate, pouco leite e espuma",
      img: "./public/card-img9.png",
      type: ["Tradicional", "Com leite"],
      price: 15.0,
      count: 0,
      id: 9,
      total: 0,
      favorite: false,
      isSelected: false,
    },
    {
      name: "Chocolate Quente",
      description:
        "Bebida feita com chocolate dissolvido no leite quente e café",
      img: "./public/card-img10.png",
      type: ["Especial", "Com leite"],
      price: 11.7,
      count: 0,
      id: 10,
      total: 0,
      favorite: false,
      isSelected: false,
    },
    {
      name: "Cubano",
      description:
        "Drink gelado de café expresso com rum, creme de leite e hortelã",
      img: "./public/card-img11.png",
      type: ["Especial", "Alcoólico", "Gelado"],
      price: 18.9,
      count: 0,
      id: 11,
      total: 0,
      favorite: false,
      isSelected: false,
    },
    {
      name: "Havaiano",
      description: "Bebida adocicada preparada com café e leite de coco",
      img: "./public/card-img12.png",
      type: ["Especial"],
      price: 13.3,
      count: 0,
      id: 12,
      total: 0,
      favorite: false,
      isSelected: false,
    },
    {
      name: "Árabe",
      description: "Bebida preparada com grãos de café árabe e especiarias",
      img: "./public/card-img13.png",
      type: ["Especial"],
      price: 16.4,
      count: 0,
      id: 13,
      total: 0,
      favorite: false,
      isSelected: false,
    },
    {
      name: "Irlandês",
      description: "Bebida a base de café, uísque irlandês, açúcar e chantilly",
      img: "./public/card-img14.png",
      type: ["Especial", "Alcoólico"],
      price: 19.5,
      count: 0,
      id: 14,
      total: 0,
      favorite: false,
      isSelected: false,
    },
  ]);

  

  return (
    <DataContext.Provider value={{ card, setCard }}>
      {children}
    </DataContext.Provider>
  );
}

export default CardProvider;
